### ISSUE TITLE
New repository request for platform specific Bridge IC code

### ISSUE THREAD

**Issue by HCL-BMC** [openbmc/technical-oversight-forum#11]
Hi All,

In our system (OCP multi host system) Bridge IC acts as a bridge between host and BMC. All the IPMI commands (including oem commands) from the host are routed to Bridge IC and Bridge IC will forward those commands to BMC.  Similarly, BMC will route IPMI commands to Bridge IC and it's forward to host.

We wanted to put this platform specific Bridge IC related code and ipmb commands handling code. So, we need a new repository to add these codes.

Example : 
All firmware update(VR, ME, BIC) is happening via the ipmb commands(oem) using this Bridge IC only.

Could you please help to create a repository for this.

Please refer this mailing list conversation with same subject for more details.
https://lists.ozlabs.org/pipermail/openbmc/2022-January/028769.html
https://lists.ozlabs.org/pipermail/openbmc/2022-January/028915.html

Thanks,
Kumar.

**Comment by edtanous** [comment]
Not enough details on this request.  Who will be the maintainer?  Kumar?

https://gerrit.openbmc-project.xyz/q/owner:thangavel.k%2540hcl.com shows a 50% ish hit rate for getting patches merged into the existing projects, with 50% or so abandoned.  That doesn't inspire confidence in his ability to maintain his own subproject.

 Where's the design doc?  How does this design differ from say, IPMBSensor (which is also an application that connects to IPMI devices to handle this kind of thing).  I know some of these answers from conversations with Kumar, but design docs should be written and crosslinked.  Will this use EM or PIM?  Can anything be made generic for all IPMB devices?  Will this use a linux device driver for interacting with the BIC?  Or will it use userspace?

Would like to see more discussion around this to ensure this isn't just a code drop of HCL/FB specific code, given that it's using a FB specific interface, and there are lots of devices that support IPMB.  NodeManagerProxy is a pretty similar application in its description (uses IPMB, forwards sensors, ect) that's specific to ME (although intel hasn't upstreamed it yet) I wonder if those could be combined in any way to get the best overall result for the project?

**Comment by rthomaiy** [comment]
Hi Kumar, 
You want repo for keeping the Code running in the Bridge IC or the OpenBMC FW code which communicates with the Bridge IC?

**Comment by edtanous** [comment]
> It has a set of oem commands that will bridge ipmb sensors, ME etc

Considering that the above description is essentially a good description of IPMBSensor (bridging sensors from ME), I'd like to make sure that the code isn't duplicated.  Please make sure that is addressed in your design.


> Patrick can be Maintainer for this new repository.

Just as a matter of process, maybe he should open a new request for this once the design doc is open, to make his volunteering explicit?

**Comment by williamspatrick** [comment]
Closing until the reworked design is ready.  Please reopen when it is.
