### ISSUE TITLE
Request to create 2 new repositories for "bios-bmc-smm-error-logger"

### ISSUE THREAD

**Issue by brandonkimbk** [openbmc/technical-oversight-forum#14]
Copied from a mail I sent out last week: https://lore.kernel.org/all/CALGRKGMgs4m=h6udakL_hcUugrPFyvTt+RefBjyVinE9ReGXyQ@mail.gmail.com/

------------------

Hello,

Following the design doc review here:
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/52109/12

I would like to request 2 new repositories as listed in the new
"Organizational" section of the design template that I filled out
here: https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/53169/2

bios-bmc-smm-error-logger
  - This repository will implement the daemon described in this document
  - Proposed maintainer: [wltu@google.com](mailto:wltu@google.com) , [brandonkim@google.com](mailto:brandonkim@google.com)

libbej
  - This repository will follow the PLDM RDE specification as much as possible
    for RDE BEJ decoding (initially, encoding may come in the future) and will
    host a library written in C
  - Proposed maintainer: [wltu@google.com](mailto:wltu@google.com) , [brandonkim@google.com](mailto:brandonkim@google.com)

Thank you,
Brandon

**Comment by dkodihal** [comment]
Would libbej also implement the PLDM RDE specification, or is it a generic JSON to BEJ converter? If the former, why not  implement it under the pldm repository?

**Comment by brandonkimbk** [comment]
Could be a good discussion to have within the design doc as well.

It is supposed to be the former, so maybe the pldm repository (I'm guessing openbmc/pldm?) is correct. we do want to have it written in C though.

**Comment by williamspatrick** [comment]
> It is supposed to be the former, so maybe the pldm repository (I'm guessing openbmc/pldm?) is correct. we do want to have it written in C though.

My understanding is that we are writing this in C in order to be able to reuse it in other environments, which might not support C++ (especially uCs).  With this in mind, I believe it belongs in its own repository and not tied into PLDM.  The special "-Dbuild-only-library" meson options are a pain for maintenance and it is far easier to create a normal dependency / subproject-wrap.  This will also make it far easier to incorporate into uC build environments like Zephyr.

If we're not going to make it easy for inclusion in other projects then we shouldn't bother restricting ourselves to C either.

**Comment by edtanous** [comment]
+1 to everything Patrick said.

**Comment by amboar** [comment]
Yes, separate repos please. The fewer knobs we have to configure builds the better.

**Comment by brandonkimbk** [comment]
I may have overheard that these repos were approved during the TOF meeting this week. Is there anything else needed for the repo creation?

**Comment by williamspatrick** [comment]
> I may have overheard that these repos were approved during the TOF meeting this week. Is there anything else needed for the repo creation?

I'll log the minutes / outcome here in a bit.  @bradbishop will make the repos but I think we're expecting a few minor tweaks before you put some code in based on the discussion.

**Comment by brandonkimbk** [comment]
Great, thanks for the update!

**Comment by bradbishop** [comment]
> @bradbishop will make the repos

These are live now:

https://github.com/openbmc/libbej
https://github.com/openbmc/bios-bmc-smm-error-logger

**Comment by brandonkimbk** [comment]
Great, thank you so much!

**Comment by brandonkimbk** [comment]
Got it.

@bradbishop - is there a GitHub group that also needs to be created to grant +2 reviewers?

**Comment by brandonkimbk** [comment]
Just a small ping since it looks like no +2 permissions have been granted yet for the new repos

**Comment by bradbishop** [comment]
> Got it.
> 
> @bradbishop - is there a GitHub group that also needs to be created to grant +2 reviewers?

I had only added @edtanous.  I added you now as well Brandon - can you give it another try?
