### ISSUE TITLE
Request to create one new repository for "kunlun-ipmi-oem"

### ISSUE THREAD

**Issue by xiuzhi11** [openbmc/technical-oversight-forum#15]
Hello,

I would like to request 1 new repository:
    kunlun-ipmi-oem
This component is intended to provide kunlun-specific IPMI command handlers for OpenBMC. These handlers are intended to integrate Kunlun OpenBMC  with servers based on x86,aarch64,mips, loongarch architectures in China.

This repository will implement:
    1) override existing implementation of standard IPMI commands to comply with kunlun-specific solutions,
    2) provide implementation for non-standard OEM extensions.

Proposed maintainer: [xzcheng@zd-tech.com.cn](mailto:xzcheng@zd-tech.com.cn) , [kbai@zd-tech.com.cn](mailto:kbai@zd-tech.com.cn)

Thank you,
Xiuzhi

**Comment by williamspatrick** [comment]
Can you elaborate on what “kunlun” is?  Is this a machine, a company, or an architecture?  What is the relationship between it and zd-tech?  You mentioned a pretty big set of processor architectures.

**Comment by xiuzhi11** [comment]
'kunlun BMC'  is the name of  BMC of ZD-tech company. 
We have  integrated Kunlun BMC to these kinds of servers based on severial CPU architedtures mentioned above for Lenovo,Sugon,Inspur etc. Every company  has   extra costomized IPMI OEM commands . The kunlun-ipmi-oem has the ipmi commands set  of kunlun BMC using on  the servers. I hope the kunlun-ipmi-oem commands can be used by more server companies .

**Comment by xiuzhi11** [comment]
'kunlun BMC'  is the name of  BMC of ZD-tech company. 
We have  integrated Kunlun BMC to these kinds of servers based on severial CPU architedtures mentioned above for Lenovo,Sugon,Inspur etc. Every company  has   extra costomized IPMI OEM commands . The kunlun-ipmi-oem has the ipmi commands set  of kunlun BMC using on  the servers. I hope the kunlun-ipmi-oem commands can be used by more server companies .

**Comment by williamspatrick** [comment]
> 'kunlun BMC' is the name of BMC of ZD-tech company.

Typically we've named these based on companies and not based on an internal codename (or product name) you have as a company.  Do you have any concerns with this being `zdtech-ipmi-oem` or something similar to follow this pattern?

**Comment by edtanous** [comment]
> Do you have any concerns with this being `zdtech-ipmi-oem` or something similar to follow this pattern?

+1

**Comment by williamspatrick** [comment]
@xiuzhi11 - Also, I don't see a current `meta-<company>` in openbmc/openbmc for ZD-tech.  I'm slightly surprised you're asking for an OEM IPMI repo if there isn't a machine upstreamed.  Do you intend to also submit at least one machine?

**Comment by xiuzhi11** [comment]
> > 'kunlun BMC' is the name of BMC of ZD-tech company.
> 
> Typically we've named these based on companies and not based on an internal codename (or product name) you have as a company. Do you have any concerns with this being `zdtech-ipmi-oem` or something similar to follow this pattern?

'zdtech-ipmi-oem' is okay for me, thanks your advice.

**Comment by xiuzhi11** [comment]
> @xiuzhi11 - Also, I don't see a current `meta-<company>` in openbmc/openbmc for ZD-tech. I'm slightly surprised you're asking for an OEM IPMI repo if there isn't a machine upstreamed. Do you intend to also submit at least one machine?
This purpose of ipmi-oem component is for a serial of servers , meta-zdtech maybe is the next submit. Thanks.

**Comment by xiuzhi11** [comment]
I prefer use kunluntech-ipmi-oem or kunlun-ipmi-oem because my company name has changed to  Kunlun Technology (Beijing) Co., Ltd from ZD Technology Co. Ltd last month.

**Comment by bradbishop** [comment]
@xiuzhi11 I sent Github invites to the email addresses above.  Those should get accepted so that they can merge code in Gerrit.

**Comment by amboar** [comment]
Can we close this?
