### ISSUE TITLE
Architectural decision: physical topology for inventory items

### ISSUE THREAD

**Issue by BenjaminFair** [openbmc/technical-oversight-forum#18]
Hello,

I'd like to get consensus on this design review: https://gerrit.openbmc.org/c/openbmc/docs/+/54205

It has gone through multiple iterations and there seems to be broad agreement on all points except for the exact representation of relationships between inventory items on D-Bus. The options are:

1) [Associations](https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/Association/Definitions.interface.yaml) for all relationships between inventory items
2) A mixture of Associations and path hierarchies depending on the type of relationship between items

My proposal is option 1. Additional details are available in the Gerrit review

**Comment by gtmills** [comment]
https://gerrit.openbmc.org/c/openbmc/docs/+/41468 is a similar design doc

**Comment by williamspatrick** [comment]
The decision from the TOF was to move forward with the design in 54205 and this option:

> Associations for all relationships between inventory items
