### ISSUE TITLE
Design decision: Dynamic Redfish Authorization

### ISSUE THREAD

**Issue by FighterNan** [openbmc/technical-oversight-forum#19]
https://gerrit.openbmc.org/c/openbmc/docs/+/56401

This document proposes a design to implement a dynamic authorization system for the Redfish interface, so that system managers can update authorization behaviors without recompile and even service reset.

There are several +1s from different reviewers from various aspects:

1. Patrick Williams: overall design
2. Joseph Reynolds: security
3. Ed Tanous: BMCWeb

Note: the +1s disappeared since I updated some minor changes. From the patch set diff, one can clearly see no major updates are made since the last +1.

However, the design has been pending since then. I pinged related maintainers offline but they still didn't get a chance to reply to this design review.

Ask for the TOR members: could you help decide if this design is ready to be merged. If so, please merge the design so that the implementation can start to go in?

**Comment by williamspatrick** [comment]
Two questions:

1. Were there any points of contention in the design?
2. Were there maintainers of specific repositories you felt needed additional feedback?

I suspect we don't need the TOF to take any action on this, but we should just merge it if the design was given plenty of opportunity for feedback and there are not any outstanding contentions.

**Comment by FighterNan** [comment]
> Were there any points of contention in the design?

I don't believe the current version of the design has major contention.

> Were there maintainers of specific repositories you felt needed additional feedback?

I was told to request feedback from both the security group and maintainers of phosphor-user-manager. Both have looked at the design. But I just missed +1 from maintainers of phosphor-user-manager.

> I suspect we don't need the TOF to take any action on this, but we should just merge it if the design was given plenty of opportunity for feedback and there are not any outstanding contentions.

I will appreciate it if we can get the design merged. I believe I have called enough attention to stakeholders.

**Comment by williamspatrick** [comment]
I've given the doc commit a +2.  It seems like a lack of maintainer feedback rather than any specific contentions.
