### ISSUE TITLE
Document guidelines/requirements for becoming a maintainer

### ISSUE THREAD

**Issue by yuennancy** [openbmc/technical-oversight-forum#22]
There are several people on my team, and adjacent teams that have expressed interest in becoming a maintainer.   Their biggest frustration is that there's not clear guidelines or requirements to becoming a maintainer; it seems like magic.

I would really help for the TOF to document what someone needs to demonstrate to show they are ready to be a maintainer, how does one earn the trust from others to become a maintainer.  What kinds of contributions, over what timeframe?  Not looking for a checklist, but maybe a lose set of requirements or guidelines.

The other way I've seen this done is through sponsorship.  New maintainers are sponsored by leaders in the community, trained and when ready as given the role of maintainer.  I borrowed from Kubernetes [community membership page.](https://github.com/kubernetes/community/blob/master/community-membership.md)  Kubernetes is more strict, even members have to be sponsored, but I think that's under the assumption that members move up the contributor chain to eventually approver and owner

**Comment by williamspatrick** [comment]
@edtanous  attempted to resolve this via https://gerrit.openbmc.org/c/openbmc/docs/+/60215 / https://github.com/openbmc/docs/blob/master/community-membership.md .  The TOF had reviewed and approved of this design document.  Closing issue.
