### ISSUE TITLE
Request for a OpenBMC repository [preferably bmc-ras or oob-ras or bmc-crashdump or oob-crashdump]

### ISSUE THREAD

**Issue by supven01** [openbmc/technical-oversight-forum#24]
Initial maintainers

Supreeth Venkatesh [Supreeth.Venkatesh@amd.com] 
Abinaya Dhandapani [Abinaya.Dhandapani@amd.com]

Please refer to https://lists.ozlabs.org/pipermail/openbmc/2023-March/033157.html
for mailing list discussion.

**Comment by edtanous** [comment]
How does your request differ from: https://github.com/openbmc/bios-bmc-smm-error-logger

which appears to be a repo claiming similar ras functionality?

**Comment by supven01** [comment]
@edtanous - Thank you for the comment. The design document you referenced seems to point to Redfish Device Enablement [RDE] and BIOS <-> BMC Host interface. However, the request we are referring to, does *not* involve System Mangement Mode [SMM] or BIOS. We will be using Advanced Platform Management Link [APML] specification: https://www.amd.com/system/files/TechDocs/57019-A0-PUB_3.00.zip
Which involves communication between BMC and SMU (consider it as separate satellite management controller separate from x86 core)

**Comment by dhruvibm** [comment]
Based on the design in the mail, phosphor-debug-collector can be used for hosting used for this dump right?

**Comment by supven01** [comment]
> Based on the design in the mail, phosphor-debug-collector can be used for hosting used for this data collection right?

CPER type logs [/var/lib/bmc-ras/1.cper, /var/lib/bmc-ras/2.cper, etc] will be generated by the bmc-ras repository.  Once those files are generated. Data collection can be done by phosphor-debug-collector or a cloud service that invokes the Redfish LogServices to collect data periodically or via Redfish Event Notification.

**Comment by edtanous** [comment]
> However, the request we are referring to, does not involve System Mangement Mode [SMM] or BIOS. 

From a bmc perspective, whether messages are coming from SMM, BIOS, or something else is immaterial, to the bmc, the commands look the same.  If you don't want to use RDE to transfer CPER logs, that is easily configurable in the repository.

> Which involves communication between BMC and SMU (consider it as separate satellite management controller separate from x86 core)

Yep, this is exactly how other system daemons operate today.  I don't feel like this needs a new repository.  If you want to add a new daemon, it can be added to one of the existing host interface repositories, while reusing the existing code where possible.

Happy to discuss if that's unacceptable.

**Comment by MichaelJeiShen** [comment]
Hi Ed,
Does Supreeth answer your question? or do you still have any concern?

**Comment by edtanous** [comment]
Since this submission was made, the TOF came up with the repo creation template [here](https://github.com/openbmc/technical-oversight-forum/blob/main/.github/ISSUE_TEMPLATE/repo_request.md), to answer questions about general requests for the repos that will help these move along faster in the future.  Please update your request with the repo-template parameters filled out.

For consideration of the requested maintainers:
The Supreeth doesn't seem to meet the activity requirements of being a maintainer or active:
https://gerrit.openbmc.org/q/owner:supreeth.venkatesh%2540amd.com

And Abinaya doesn't appear to have any participation in the project that I can find:
https://gerrit.openbmc.org/q/owner:%2522abinayaddhandapani%2522

Neither appear on the H123  roll call:
https://github.com/openbmc/tof-election/blob/main/2023H1/rollcall.json

Am I missing participation elsewhere?  It is highly likely that someone would be willing to mentor either of you in maintainership.  For that I suspect reaching out on discord is the right approach.  If I've mapped either of your names incorrectly, I apologize.

**Comment by supven01** [comment]
---
name: Create a new repository
about:
When one or more processors register a fatal error condition, then an interrupt is generated to the host processor.
The host processor in the failed state asserts the signal to indicate to the BMC that a fatal hang has occurred. [APML_ALERT# in case of AMD processor family]
BMC RAS application listens on the event [APML_ALERT# in case of AMD processor family].

Upon detection of FATAL error event , BMC will check the status register of the host processor [implementation defined method] to see if the assertion is due to the fatal error. Upon fatal error, BMC will attempt to harvest crash data
from all processors. [via the APML interface (mailbox) in case of AMD processor family].

BMC will generate a single raw crashdump record and saves it in non-volatile location /var/lib/bmc-ras.

Since the above process is AMD processor specific, it needs a separate repository.

title:
labels: ""
assignees: "Ed Tanous", "Patrick Williams"
---

**Design Document**
https://lists.ozlabs.org/pipermail/openbmc/2023-March/033157.html

**Naming**
amd-ras
amd-crashdump

**Maintainers**
Supreeth Venkatesh
Abinaya Dhandapani

Yes. Contributions from AMD have been not that active because we were stuck in legal approval process for a while.
However, it will not be so anymore, as we have legal approval. AMD will actively be contributing to the open source upstream.

Thank you for encouraging contributions to the OpenBMC Linux foundation project. Abinaya will reach out on Discord.
There are no clear guidelines or requirements to becoming a maintainer. It would be a great initiative, if Technical Oversight forum comes up with a detailed document. It would be greatly appreciated.

P.S: I have been the maintainer of meta-amd for a long time including being on TSC for a short time.

**Comment by amboar** [comment]
> Yes. Contributions from AMD have been not that active because we were stuck in legal approval process for a while. However, it will not be so anymore, as we have legal approval. AMD will actively be contributing to the open source upstream.

Great news!

> Thank you for encouraging contributions to the OpenBMC Linux foundation project. Abinaya will reach out on Discord. There are no clear guidelines or requirements to becoming a maintainer. It would be a great initiative, if Technical Oversight forum comes up with a detailed document. It would be greatly appreciated.

Recently the following document was merged, which should help:

https://github.com/openbmc/docs/blob/master/community-membership.md

**Comment by supven01** [comment]
@williamspatrick @edtanous - Have I justified the basis for creation of the new repo?  I would be happy to answer the questions if you have any. We are excited to start contributing to this repo as per OpenBMC guidelines/conventions with support from all of the community members. Thanks for your guidance in advance.

**Comment by williamspatrick** [comment]
@supven01 I don't know where we ended up with this.  I know there was some discussions about dbus interfaces, etc.  Are you still looking for a new repository to be created?  Do you have a design document proposal in Gerrit?

**Comment by supven01** [comment]
Yes. We are still looking for a repository to be modeled after https://github.com/AMDESE/amd-bmc-ras.
I had sent an RFC few months back. I can put out a design document on Gerrit.

**Comment by williamspatrick** [comment]
> I can put out a design document on Gerrit.

Please.  That's the best way to get feedback incorporated and make sure we're aligned with the direction.

**Comment by williamspatrick** [comment]
Please reopen this issue once Gerrit design doc is ready for review.

**Comment by ojayanth** [comment]
Gerrit Design document link https://gerrit.openbmc.org/c/openbmc/docs/+/68440

**Comment by williamspatrick** [comment]
> Gerrit Design document link https://gerrit.openbmc.org/c/openbmc/docs/+/68440

The doc is listed as WIP and doesn't seem to have incorporated any feedback from here.  I don't think we are ready to reopen this / solicit approval from the TOF.  Do you agree?

**Comment by ojayanth** [comment]
https://gerrit.openbmc.org/c/openbmc/docs/+/68440 active now.

**Comment by supven01** [comment]
Can we re-open the issue? Now that we have the (https://gerrit.openbmc.org/c/openbmc/docs/+/68440)
