### ISSUE TITLE
Request to create a new repository for License service support

### ISSUE THREAD

**Issue by raviteja-b** [openbmc/technical-oversight-forum#28]
**Design Document** 
License service design proposal :
https://gerrit.openbmc.org/c/openbmc/docs/+/64710

D-bus Interfaces :
https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/64485/

Redfish license service schema:
https://redfish.dmtf.org/schemas/v1/LicenseService.v1_1_0.json
https://redfish.dmtf.org/schemas/v1/License.v1_1_1.json

**Naming** List at least two possible names for this repository. 
phosphor-license-manager
phosphor-license-service

**Maintainers** List the maintainer(s) for this repository. 
Ravi Teja <raviteja28031990@gmail.com>
Sunitha Harish <sunithaharish04@gmail.com>

**Comment by raviteja-b** [comment]
Hi all 

This is a request for creating new repository called phopshor-license-manager to implement license feature in OpenBMC.
licenses  are supposed to be uploaded by clients to unlock some of host hardware resources like processor, memory and cores etc.
plan it use to this license manager repository for implementation of license d-bus app which hosts license install method and license entry objects.

**Comment by williamspatrick** [comment]
I think we need more of a design here. How does the license server work and how are other repositories expected to interact with it?

I am assuming you want more than “upload a file” and “expose the parsed contents of that file over Redfish”. You actually want the BMC and/or other firmwares to do the enforcement of the license… how are you proposing this to work?

**Comment by raviteja-b** [comment]
> I think we need more of a design here. How does the license server work and how are other repositories expected to interact with it?
> 
> I am assuming you want more than “upload a file” and “expose the parsed contents of that file over Redfish”. You actually want the BMC and/or other firmwares to do the enforcement of the license… how are you proposing this to work?

Hi Patrick 
License service D-bus app will be using PLDM interfaces to send this license to Host and Host installs this given license & sends a json file of installed licenses to BMC through PLDM.
License D-bus app parses this license json content and populates D-bus objects.

**Comment by williamspatrick** [comment]
> License service D-bus app will be using PLDM interfaces to send this license to Host and Host installs this given license & sends a json file of installed licenses to BMC through PLDM.
> License D-bus app parses this license json content and populates D-bus objects.

These are the kind of details I'd expect to see in a design document.  Please follow the design document template, upload to Gerrit, and update your repository request with a pointer to this.

As the repository request issue says:
> Provide a link to the document outlining why this repository is required.

Maybe we should be clearer but we were expecting this to be a link to a design document proposal.

**Comment by amboar** [comment]
> Maybe we should be clearer but we were expecting this to be a link to a design document proposal.

I've pushed a patch that hopefully helps:

https://gerrit.openbmc.org/c/openbmc/technical-oversight-forum/+/64591

@raviteja-b I think it would be helpful to assume that patch above will be merged and front-run it by adding the design document link and appropriate maintainer evidence to this issue as soon as possible.

However, another hurdle you have to clear is that the problem of license management has been discussed previously in the community and wasn't very well received. Please read through the discussion and argument across all responses to this thread:

https://lore.kernel.org/openbmc/CAMhqiMoFAHcUk0nO_xoOubcZqF_dPDFweqsttTULRJK38o1Ung@mail.gmail.com/

From my perspective, you must articulate what you think is different this time around, and why those differences warrant an expectation of a different outcome.

**Comment by raviteja-b** [comment]
> > License service D-bus app will be using PLDM interfaces to send this license to Host and Host installs this given license & sends a json file of installed licenses to BMC through PLDM.
> > License D-bus app parses this license json content and populates D-bus objects.
> 
> These are the kind of details I'd expect to see in a design document. Please follow the design document template, upload to Gerrit, and update your repository request with a pointer to this.
> 
> As the repository request issue says:
> 
> > Provide a link to the document outlining why this repository is required.
> 
> Maybe we should be clearer but we were expecting this to be a link to a design document proposal.

sure Patrick, will push a design proposal

**Comment by raviteja-b** [comment]
> > Maybe we should be clearer but we were expecting this to be a link to a design document proposal.
> 
> I've pushed a patch that hopefully helps:
> 
> https://gerrit.openbmc.org/c/openbmc/technical-oversight-forum/+/64591
> 
> @raviteja-b I think it would be helpful to assume that patch above will be merged and front-run it by adding the design document link and appropriate maintainer evidence to this issue as soon as possible.
> 
> However, another hurdle you have to clear is that the problem of license management has been discussed previously in the community and wasn't very well received. Please read through the discussion and argument across all responses to this thread:
> 
> https://lore.kernel.org/openbmc/CAMhqiMoFAHcUk0nO_xoOubcZqF_dPDFweqsttTULRJK38o1Ung@mail.gmail.com/
> 
> From my perspective, you must articulate what you think is different this time around, and why those differences warrant an expectation of a different outcome.
Sure @amboar. will try capture all these details in a design document.

**Comment by raviteja-b** [comment]
> > > License service D-bus app will be using PLDM interfaces to send this license to Host and Host installs this given license & sends a json file of installed licenses to BMC through PLDM.
> > > License D-bus app parses this license json content and populates D-bus objects.
> > 
> > 
> > These are the kind of details I'd expect to see in a design document. Please follow the design document template, upload to Gerrit, and update your repository request with a pointer to this.
> > As the repository request issue says:
> > > Provide a link to the document outlining why this repository is required.
> > 
> > 
> > Maybe we should be clearer but we were expecting this to be a link to a design document proposal.
> 
> sure Patrick, will push a design proposal

Here is design doc https://gerrit.openbmc.org/c/openbmc/docs/+/64710

**Comment by williamspatrick** [comment]
Please reopen when the design document is complete. There are at least 3 sections at the end that aren’t filled in.
