### ISSUE TITLE
Use of rules screening for discord

### ISSUE THREAD

**Issue by amboar** [openbmc/technical-oversight-forum#29]
**Background** 
Discord supports [Rules Screening](https://support.discord.com/hc/en-us/articles/1500000466882-Rules-Screening-FAQ), which requires people joining the community to confirm they understand the community expectations for the server.

A few ideas for community rules have emerged recently:

1. "Don't post in multiple channels the same question.  If you do, because you realize you posted in the wrong one initially, delete the original message."
2. "Don't send uninvited private messages to people on the server for support questions."
3. "if you're asking questions here then there's a fair chance you're not paying anyone to answer them. Given that, no-one here owes you anything, however some people may choose to help. If they do, that's entirely voluntary, and doesn't come with deadlines"
4. "Don’t post previously unknown security vulnerabilities"
5. "Don't expect a high-effort answer to a low-effort question"

**Questions**
1. Should we enable rules screening?
2. Are each of the rules above reasonable?
3. Can we improve the wording of the suggestions above?
4. What other rules should we consider?

**Comment by zevweiss** [comment]
> What other rules should we consider?

Perhaps "please copy and paste text (ideally using triple-backticks to format nicely) instead of posting screenshots"?

**Comment by jmbills** [comment]
Do we need to mention anything about general etiquette? professionalism, politeness, consideration, etc.?

Should we highlight the Code of Conduct and that it applies to Discord chats: https://github.com/openbmc/docs/blob/master/code-of-conduct.md?

**Comment by williamspatrick** [comment]
> Should we highlight the Code of Conduct and that it applies to Discord chats:

That currently is the _only_ rule. I’ll make sure a reference to the CoC is preserved.

**Comment by amboar** [comment]
[The X-Y problem](https://web.archive.org/web/20220104214000/https://mywiki.wooledge.org/XyProblem)

**Comment by gtmills** [comment]
Looks great. Thanks, Andrew! Minor feedback: be consistent with capitalization and punctuation and keep them simple if possible. Maybe more like:  

"Don't post in multiple channels the same question."

"Don't send uninvited private messages to people on the server for support questions."

"If you're asking questions here, there's a fair chance you're not paying anyone to answer them. Given that, no one here owes you anything; however, some people may choose to help. If they do, that's entirely voluntary and doesn't come with deadlines."

"Don't post previously unknown security vulnerabilities."

"Don't expect a high-effort answer to a low-effort question."

**Comment by amboar** [comment]
This seems to have general support. I'm going to add these to Discord and we can back them out if anyone thinks they're inappropriate in some way.

**Comment by amboar** [comment]
I've wordsmithed @gtmills 's list a little further and enabled rules screening.

**Comment by amboar** [comment]
For the record, here is what I wrote:

![Screenshot from 2023-10-11 14-41-59](https://github.com/openbmc/technical-oversight-forum/assets/526481/7fddb7da-19ef-4e4c-9eae-96b146413c78)
