### ISSUE TITLE
Unresponsive code-reviews (openbmc/telemetry)

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/technical-oversight-forum#32]
**Background** 

https://github.com/openbmc/docs/blob/master/process/subproject-maintainership.md

**Questions** 

- Telemetry
   - https://gerrit.openbmc.org/c/openbmc/telemetry/+/64867
   - https://gerrit.openbmc.org/c/openbmc/telemetry/+/67240
   - https://gerrit.openbmc.org/c/openbmc/telemetry/+/66007

**Comment by amboar** [comment]
https://lore.kernel.org/openbmc/47c53da80f585dac8e1450b20c5855ede960d243.camel@codeconstruct.com.au/T/#u

**Comment by williamspatrick** [comment]
Resolved.
