### ISSUE TITLE
Request to create one new repository for "iei-ipmi-oem"

### ISSUE THREAD

**Issue by lxwinspur** [openbmc/technical-oversight-forum#33]
Hey, all:

We would like to create a new repository: `iei-ipmi-oem`
This repository provides IEIsystems-specific IPMI command handlers for x86 and power platforms for OpenBMC.

Proposed maintainer: liuxiwei@ieisystem.com

Thanks
BRs
George Liu

**Comment by edtanous** [comment]
IMO, ideally some day we'd consolidate all the OEM ipmi repos into https://github.com/openbmc/phosphor-host-ipmid, which would help to not have to create a new repo every time a new OEM command set gets added.

Given that so far as I know nobody is willing to take that on at the moment, this proposal is following exactly the same pattern as other OEM commands, and the proposed maintainer has a long history of contributions, I have no objections to creating a new repo.

**Comment by amboar** [comment]
@edtanous I did intend to make the same comment about merging all the IPMI OEM repos into phosphor-host-ipmid. But, I don't have much of a stake in IPMI at the moment, so I guess we carry on.

**Comment by williamspatrick** [comment]
@lxwinspur Should we rename the inspur repository?  The meta layer was deleted and I assume your bios has significant overlap.

**Comment by lxwinspur** [comment]
> @lxwinspur Should we rename the inspur repository? 

I am fine with that. :)

**Comment by lxwinspur** [comment]
@bradbishop 
Could you please create a new repo or rename `inspur-ipmi-oem` to `iei-ipmi-oem`?
Thanks.

**Comment by williamspatrick** [comment]
> @bradbishop Could you please create a new repo or rename `inspur-ipmi-oem` to `iei-ipmi-oem`? Thanks.

The TOF can get this taken care of. Please be patient.

**Comment by lxwinspur** [comment]
Hi @williamspatrick @bradbishop 
Any progress?
