### ISSUE TITLE
Libcper repository request

### ISSUE THREAD

**Issue by edtanous** [openbmc/technical-oversight-forum#35]
**Design Document** 

https://gerrit.openbmc.org/c/openbmc/docs/+/71577

**Naming**

libcper
cper-decoding

**Maintainers**
Ed Tanous <edtanous>

I am a member of the TOF, and an active community member.

**Comment by amboar** [comment]
I prefer `libcper`

**Comment by edtanous** [comment]
I agree.  The template asks for 2 suggestions so I did as the template asked .

**Comment by geissonator** [comment]
My only concern is that libcper kind of locks you into just providing a library (or having an inconsistent name). It seemed like things were still a bit open in the design with where we go after getting the library in place. Are you sure you want to lock yourself into this repo only having a library?

**Comment by amboar** [comment]
I think it's a good idea to keep the concept of the repo focused. Naming it `libcper` provides some friction against expanding its responsibilities. But also, that's not to say that supporting applications can't be implemented in it. For example, we have a few applications built out of libmctp.

**Comment by wak-google** [comment]
Yeah, so long as we are committing to keeping this repo focused on providing a CPER encoding / decoding library libcper is fine.

**Comment by edtanous** [comment]
+1 to Arj.  Also, not changing the name compared to the ARM-built one seems like a good idea, so that searching for the old name results in this one showing up.
