### ISSUE TITLE
phosphor-network maintainer responsiveness

### ISSUE THREAD

**Issue by Howitzer105mm** [openbmc/technical-oversight-forum#36]
**Background** The maintainers for phosphor-network are not responding

**Questions** 
Is this the correct forum to request action regarding code reviews from phosphor-network maintainers?
I have several submissions that have been peer reviewed, and do not appear to have been addressed by either phosphor-network maintainer. This in spite of updating the commits with requests for action.

https://gerrit.openbmc.org/c/openbmc/phosphor-networkd/+/69450 May 30 Third +1 applied. Nudged 17 June.
https://gerrit.openbmc.org/c/openbmc/phosphor-networkd/+/70004  Apr 26 Third +1 applied. Nudged 29 May
https://gerrit.openbmc.org/c/openbmc/phosphor-networkd/+/69449  May 29 Second +1 applied. Nudged 29 May

**Comment by wak-google** [comment]
Yeah, this is my fault for looking away from all these upstream reviews. Will go through them now.

**Comment by amboar** [comment]
> Is this the correct forum to request action regarding code reviews from phosphor-network maintainers?

Yep, raising a complaint to the TOF as you've done here is the expected way to highlight such issues, given you've already tried to get attention from the maintainers.

Hopefully @wak-google can help make progress with your work.

As background, a while back I put together some guidelines for addressing stuck patches and unresponsive maintainers. You can find more here:

https://github.com/openbmc/docs/blob/master/process/subproject-maintainership.md

It's a bit formal in parts, but the formality was my attempt to set limits on both the scope of the document and the actions the TOF could take. Hopefully that helps set expectations.

**Comment by williamspatrick** [comment]
Resolved.
