### ISSUE TITLE
New repository for device-tree VPD to Dbus service

### ISSUE THREAD

**Issue by csides-hpe** [openbmc/technical-oversight-forum#38]
Hi folks, 

I'm looking for input on a proposal for a new repo to host a VPD (HW ID data) -> Dbus service involved in the Entity-Manager probe/HW discovery processes. The daemon allows Entity-Manager to recognize hardware with Vital Product Data (VPD) discovered via well-known device-tree nodes like 'model' instead of from an I2C-based EEPROM.

This daemon is required for Entity-Manager to be able to recognize HPe hardware, but it relies on well-defined device-tree nodes like 'model' that are not HPe-specific.

I'm currently aware of 4 existing [channel] VPD -> DBus daemons in OBMC: 

• FRU_Device (Hosted in Entity-Manager repo, the majority of platforms rely on this. IIRC, some maintainers have expressed they would rather it be hosted in a separate, non-Entity-Manager repo, but that's where it landed) https://github.com/openbmc/entity-manager/tree/master/src 

• PECI_PCIe (has own repo) https://github.com/openbmc/peci-pcie 
	
• SMBIOS_MDR (has own repo) https://github.com/openbmc/smbios-mdr 
	
• Openpower-vpd-parser (has own repo) https://github.com/openbmc/openpower-vpd-parser

I'm proposing a new [channel] VPD -> DBus service repo named "MachineContext-DeviceTree-VPD-Parser" or maybe just "DeviceTree-VPD-Parser." I like the idea of having 'vpd' in the name for easier purpose identification like the openpower-vpd-parser repo does.

Here's the current code for the daemon that would be hosted in the proposed repo. The 'MachineContextd' daemon name may be subject to change
https://gerrit.openbmc.org/c/openbmc/phosphor-u-boot-env-mgr/+/71512/6/src/machinecontextd.hpp 
https://gerrit.openbmc.org/c/openbmc/phosphor-u-boot-env-mgr/+/71512/6/src/machinecontextd.cpp 

-- any other files were only touched for requested repo-level organizational change reasons): https://gerrit.openbmc.org/c/openbmc/phosphor-u-boot-env-mgr/+/71512 

Here's the design doc for the daemon in question, which includes discussion about potential repo hosts for this service that have already been rejected for (Entity-Manager, and Phopshor-u-boot-env-mgr) in the 'Alternatives Considered' section: https://gerrit.openbmc.org/c/openbmc/docs/+/66369

The latest change to the doc includes updates to the 'Alternatives Considered' discussion about which interface and hosting repo should be relied on for this service

Main questions I'm looking to answer:

1. Does the community feel it's reasonable to create a new repo for this Device-Tree VPD -> DBus service? Assuming yes...

2. What should it be named? Would folks be okay with something like 'MachineContext-DeviceTree-VPD-Parser'?

3. How would I start on the process of creating a new repo and pushing it to Gerrit for review and discussion?

-------------------------
**Design Document** 
https://gerrit.openbmc.org/c/openbmc/docs/+/66369

**Naming** suggestions:
'MachineContext-DeviceTree-VPD-Parser'
'DeviceTree-VPD-Parser'

**Maintainers** 
Christopher.Sides@hpe.com (@CitySides) - https://gerrit.openbmc.org/q/christopher.sides@hpe.com+is:closed
Ian.Woloschin@hpe.com (@IWoloschin) - https://gerrit.openbmc.org/q/ian.woloschin@hpe.com+is:closed

**Comment by mdmillerii** [comment]
https://discord.com/channels/775381525260664832/819741065531359263/1275929514614194176

**Comment by amboar** [comment]
"devicetree-vpd-parser" is my suggestion if we're to have a new repo.

**Comment by jmbills** [comment]
`phosphor`?

**Comment by csides-hpe** [comment]
> `phosphor`?

Something I've wondered - what's the usual criteria for a repo to get 'phosphor' prepended to the name? 

I'm currently partial towards 'devicetree-vpd-parser' as a name, but 'phosphor-devicetree-vpd-parser' is good too, if that has more of a ring to it.

**Comment by williamspatrick** [comment]
All of the original repositories had phosphor prepended to ensure we did not have any name collisions with other opensource projects.  Later on, other people came on the project and didn't like typing "phosphor" for everything ( :laughing: ) and started dropping it.  There is no special "criteria".

**Comment by iwoloschin** [comment]
I'd vote for no `phosphor-` prefix unless you're also going to go and make all of the parsers have the `phosphor-` prefix. I think it'd be confusing for only one parser to have the prefix, especially if it is not the first one someone should look at.

**Comment by csides-hpe** [comment]
Any thoughts on what needs to happen to drive this topic forward? 

The initial source for the daemon we'd like to host in this repo is available @ 71512: service: device-tree node to d-bus for hw id data | https://gerrit.openbmc.org/c/openbmc/phosphor-u-boot-env-mgr/+/71512

It checks for a list of well-defined device-tree nodes ('model' and 'serial-number') at startup and writes any discovered values to D-Bus for Entity-Manager probe consumption.

The design document for the process can be found @ 66369: entity-manager hw id: vpd discover via device-tree | https://gerrit.openbmc.org/c/openbmc/docs/+/66369

I have the impression the community is generally 'good' with the design doc at this point. At last check, it was suggested a final step might be to ask the Technical Oversite Forum to discuss this 'inventory channel' addition in the context of any other channel additions TOF members may be aware of coming down the line.

Would it be worth it to create a separate 'discuss channel daemon implementation, channel design doc, and creation of a new repo as a bundle' TOF topic, or is posting in this thread good enough to get discussions kicked off?

**Comment by amboar** [comment]
> or is posting in this thread good enough

This is good enough, there will be some discussion in the next 24 hours or so.

**Comment by williamspatrick** [comment]
@csides-hpe TOF discussion consensus is to submit this as a new application in entity-manager (as is with fru-device).  Since you're adding PDI dependency and sdbusplus co-routine support, please add me as a review.  Good to also @amboar (since he's looked at your design the most) and @edtanous should be automatically added as a maintainer.
