### ISSUE TITLE
`phosphor-snmp` maintainer responsiveness

### ISSUE THREAD

**Issue by Kostr** [openbmc/technical-oversight-forum#40]
**Background** The maintainers for the `phosphor-snmp` are not responding

**Questions** Can't get any feedback on the patchset pushed in April (more than 4 months ago):
70979: meson: Fix local meson build | https://gerrit.openbmc.org/c/openbmc/phosphor-snmp/+/70979

I don't know nicknames of the maintainers in the discord to ping them there. Is there any way to merge the patchsets?

**Comment by amboar** [comment]
The nicknames are listed in the OWNERS file:

https://gerrit.openbmc.org/plugins/gitiles/openbmc/phosphor-snmp/+/a73231b23598a1ede2c43a1487df14c5ec58a96e/OWNERS

In this case, `devender` and `rgupta`. Can you try to contact them?

**Comment by williamspatrick** [comment]
Resolved
