### ISSUE TITLE
New openBMC repo for Liquid-Cooling-Leak-Detection

### ISSUE THREAD

**Issue by jagpalgill** [openbmc/technical-oversight-forum#41]
**Design Document** [Liquid Cooling Leak Detection](https://gerrit.openbmc.org/c/openbmc/docs/+/73152)

**Naming** 
- phosphor-liquid-cooling
- phosphor-liquid-leak-detection

**Maintainers** 
* Jagpal Singh Gill 
   Email: <paligill@gmail.com>
   Discord: jagpalgill
* Patrick Williams
   Email: <patrick@stwcx.xyz>
   Discord: stwcx

**Comment by amboar** [comment]
There's discussion of using EM in the linked document. Given that's the case, could this go in `dbus-sensors` rather than have a repo of its own?

**Comment by jagpalgill** [comment]
@amboar Thank you for your response. My proposal for a separate repository, specifically for phosphor-liquid-cooling, is motivated by few goals for future development. These include:

* Monitoring the health of cooling equipment (such as valve trains, meters, and pump units) through modbus or tcp connections.
* Controlling cooling equipment operations, such as turning on/off pumps or water valves.
* Implementing a state machine for maintenance modes that may involve liquid draining.

@williamspatrick @edtanous Any thoughts?

**Comment by williamspatrick** [comment]
TOF discussion today suggested we add this as a new daemon in dbus-sensors until we determine that it outgrows that location.
