### ISSUE TITLE
RFC: dbus-sensors: multiple processes managed separately

### ISSUE THREAD

**Issue by lxwinspur** [openbmc/technical-oversight-forum#42]
Currently, dbus-sensors implement multiple processes:
- psusensor
- adcsensor
- intelcpusensor
- hwmontempsensor
- ipmbsensor
- nvmesensor
- externalsensor
- mcutempsensor
- intrusionsensor
- fansensor
- exitairtempsensor

These processes have been decoupled, and putting all cpp and hpp in src is very difficult for readers.
We have several commits (https://gerrit.openbmc.org/c/openbmc/dbus-sensors/+/74790) to move each process to a separate folder for management without destroying the overall logic.

I want to ask TOF and maintainers for advice on whether this series can continue progressing. If no agreement can be reached here, I will abandon these patches. Thanks!

**Comment by williamspatrick** [comment]
This doesn't seem like something the TOF should weigh in on at this point. Please work with the repository maintainers. 

My recollection was that this was asked on Discord very recently. Please search through that discussion and make sure you have consensus with the current owners. I don't think there was much concern expressed at the time with reorganization.

**Comment by edtanous** [comment]
FWIW, I'm one of the dbus-sensors maintainers, and I support this overall, i just wasn't willing to do the work myself.  I've left a review comment on the first patch in the series.
