### ISSUE TITLE
TOF voting: accept 2022H1 rollcall

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/technical-oversight-forum#9]

**Comment by williamspatrick** [comment]
Initial roll-call for members who qualify for the 2022H1 TOF elections are found at:
    https://github.com/williamspatrick/openbmc-tof-elections/blob/main/2022H1/rollcall.json

**Comment by edtanous** [comment]
Nitpick, should we be checking this into the technical oversight committee repo (or some openbmc repo)?  Not that I think @williamspatrick would change results, or that I don't trust him, but as a general rule, we probably don't want to be pointing at peoples personal githubs, especially for documents like this.

**Comment by williamspatrick** [comment]
> should we be checking this into the technical oversight committee repo (or some openbmc repo)?

I don't really care where we host.  Currently there is nothing in this repo.  I was just biasing to move fast so I could get something out.

When this gets sent out to the mailing list as a final version (accepted by the TOF), I plan to include the pointer to the hash number, so at that point it doesn't really matter where it is hosted.

We do also need to write tooling to facilitate voting itself.  I was going to do that in the same repository and use GH PRs to ensure the vote is coming from the people in the roll-call.  This could similarly be hosted anywhere though.

**Comment by williamspatrick** [comment]
7 thumbs up votes on this.  Permalink for accepted roll-call: 

https://github.com/openbmc/tof-election/blob/b0fcea13c5433a06c6a01b32e27083e7cb74420c/2022H1/rollcall.json

Closing as accepted.

**Comment by williamspatrick** [comment]
Due to a bug in the script, I've regenerated the data.

https://github.com/openbmc/tof-election/blob/c50f5beea2be92806cebad57486474c7dabecef2/2022H1/rollcall.json

We will need to re-vote on this new data.
